name: data collection
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web-scraped
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v3
        # with:
        #   python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r Scraping/requirements.txt
        
      - name: Run Python Script
        run: python Scraping/script.py  # Replace with the name of your Python script

      - name: Find Latest File
        id: find_latest
        run: |
          latest_file=$(ls -t output2023-2024.csv* | head -n1)
          echo "::set-output name=file_name::$latest_file"
      
      - name: Save Latest File as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-file  # Specify the name of the artifact
          path: ${{ steps.find_latest.outputs.file_name }}

      # - name: Save File as Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: generated-files  # Specify the name of the artifact
      #     path: output/

      # - name: Save File as Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: generated-files  # Specify the name of the artifact
      #     path: |
      #       $(find . -name "output*" -type f)
