name: data collection
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web-scraped
        uses: actions/checkout@v2
      - name: setup python
        # uses: actions/setup-python@v3
        # with:
        #   python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f Scraping/requirements.txt ]; then pip install -r Scraping/requirements.txt
        
      - name: Run Python Script
        run: python Scraping/script.py  # Replace with the name of your Python script
