name: data collection
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web-scraped
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v3
        
      - name: Run Python Script
        run: python Scraping/script.py  # Replace with the name of your Python script
