name: Save File Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  save_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        run: python Scraping/script.py  # Replace with the name of your Python script

      # - name: Save File as Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: my-file  # Specify the name of the artifact
      #     path: generated_file.txt  # Specify the path of the file to upload
