name: Run Script Every 30 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Script
        run: python Scraping/script.py
